---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: -vv

options:
  package_manager_path: /usr/bin/microdnf

dependencies:
  galaxy:
      collections:
      - community.general
  python: []
  system: []

images:
  base_image:
      name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest

