---
- name: Configure Firewall
  hosts: "{{ ansible_limit }}"
  become: true

  vars:
    firewall:
      - port: 8081/tcp
        service: customhttp
        description: Custom HTTP service for demo, no listener on 8081
        state: enabled
        permanent: true

  tasks:
    - name: "[INCLUDE ROLE] RHEL System Role - Firewall | Configure firewalld"
      include_role:
        name: redhat.rhel_system_roles.firewall