---
- name: Configure SELinux 
  hosts: "{{ ansible_limit }}"
  become: true

  vars:
    selinux_state: permissive
    selinux_reboot_required: true

  tasks:
    - name: "[INCLUDE ROLE] RHEL System Role - SELinux | Configure SELinux"
      include_role:
        name: redhat.rhel_system_roles.selinux

