---
- name: Configure SELinux 
  hosts: "{{ ansible_limit }}"
  become: true

  vars:
    selinux_state: permissive
    selinux_reboot_required: true

  tasks:
    - name: "[INCLUDE ROLE] | RHEL System Role - SELinux"
      include_role:
        name: rhel-system-roles.selinux
  #     notify:             
  #       - restart server
      
  # handlers:
  #   - name: restart server
  #     ansible.builtin.reboot:
  #       msg: "Reboot initiated by Ansible after Linux kernel update"
  #       reboot_timeout: 3600
  #       test_command: date
