---
- name: Configure Storage
  hosts: "{{ ansible_limit }}"
  become: true

  vars:
    storage_volumes:
      - name: demo
        type: disk
        disks:
          - "/dev/sdc"
    storage_pools:
      - name: vg_extended_storage
        disks:
          - /dev/sdc1
        volumes:
          - name: lv_es_small
            size: 512
            fs_type: ext4
            mount_point: /mnt/es_small_data

  tasks:
    - name: "[INCLUDE ROLE] | RHEL System Role - SELinux"
      include_role:
        name: rhel-system-roles.storage